unstable_features = true
use_small_heuristics = true
fn_single_line = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
spaces_around_ranges = true
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 180
